spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test02_user?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

# jwt 配置
custom:
  jwt:
    # header:凭证(校验的变量名)
    header: Authorization
    # 有效期1天(单位:s)
    expire: 5184000
    # secret: 秘钥(普通字符串) 不能太短，太短可能会导致报错
    secret: 99c2918fe19d30bce25abfac8a3733ec
    # 签发者
    issuer: zeer

server:
  error:
    include-stacktrace: never
    include-message: on_param
    whitelabel:
      enabled: false


